export const EVENTS = {
  AGENT_STARTED: 'agent_started',
  PLANNING_STARTED: 'planning_started',
  PLAN_CREATED: 'plan_created',
  SEARCH_STARTED: 'search_started',
  SEARCH_COMPLETED: 'search_completed',
  PAGE_OPENED: 'page_opened',
  DATA_EXTRACTED: 'data_extracted',
  COMPARISON_STARTED: 'comparison_started',
  COMPARISON_UPDATED: 'comparison_updated',
  VERIFICATION_STARTED: 'verification_started',
  CONFLICT_DETECTED: 'conflict_detected',
  RETRY_STARTED: 'retry_started',
  VERIFICATION_COMPLETED: 'verification_completed',
  DECISION_STARTED: 'decision_started',
  RECOMMENDATION_GENERATED: 'recommendation_generated',
  AGENT_COMPLETED: 'agent_completed',
  AGENT_ERROR: 'agent_error',
};
